name: lance-env
channels:
  - defaults
dependencies:
  - ca-certificates=2023.12.12
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.8.18
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - altair==5.2.0
      - annotated-types==0.6.0
      - attrs==23.2.0
      - blinker==1.7.0
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - decorator==5.1.1
      - deprecation==2.1.0
      - filelock==3.13.1
      - fsspec==2024.3.0
      - ftfy==6.2.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - huggingface-hub==0.21.4
      - idna==3.6
      - importlib-resources==6.3.1
      - jinja2==3.1.3
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - lancedb==0.6.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - open-clip-torch==2.24.0
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.0.3
      - pillow==10.2.0
      - pkgutil-resolve-name==1.3.10
      - protobuf==4.25.3
      - py==1.11.0
      - pyarrow==15.0.0
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pydeck==0.8.1b0
      - pygments==2.17.2
      - pylance==0.10.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - ratelimiter==1.2.0.post0
      - referencing==0.34.0
      - regex==2023.12.25
      - requests==2.31.0
      - retry==0.9.2
      - rich==13.7.1
      - rpds-py==0.18.0
      - safetensors==0.4.2
      - semver==3.0.2
      - sentencepiece==0.2.0
      - six==1.16.0
      - smmap==5.0.1
      - streamlit==1.32.2
      - sympy==1.12
      - tenacity==8.2.3
      - timm==0.9.16
      - toml==0.10.2
      - toolz==0.12.1
      - torch==2.2.1
      - torchvision==0.17.1
      - tornado==6.4
      - tqdm==4.66.2
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - zipp==3.18.1
